//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "thread")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub title: String,
    pub forum: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::forum::Entity",
        from = "Column::Forum",
        to = "super::forum::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Forum,
    #[sea_orm(has_many = "super::post::Entity")]
    Post,
}

impl Related<super::forum::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Forum.def()
    }
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
